#!/usr/bin/env ruby

pdf = ARGV.shift.sub(/$/, ".pdf")

marks = File.open('pdfmarks', 'w')

h = Hash.new

while gets() do
  #expect a header line and ignore it
  next if $. == 1
  h[:bm], h[:p] = $_.chomp.split("\t")
  
  #strip wrapping double quotes
  h.each_value{|v| v.sub!(/^"(.*)"$/, '\1')}

  ##squeeze doubled double quotes
  h.each_value{|v| v.gsub!(/""/, '"')}
  
  #strip leading junk and zeros from page
  #FIXME we can probably grab the 1st page and offset all others from that?
  #or allow pgcount to be the last field
  h[:p].sub!(/.*[^0-9]0*/, '')
  offset = h[:p].to_i - 1 if $. == 2
  page = h[:p].to_i - offset

  marks.puts "[/Title (#{h[:bm]}) /Page #{page} /OUT pdfmark"
end

marks.close

gs = 'gs -dBATCH -dNOPAUSE -sPAPERSIZE=letter -sDEVICE=pdfwrite'
of = "-sOutputFile=\"#{pdf}\""
infiles = '*.pdf pdfmarks'
gs_call = "#{gs} #{of} #{infiles}"
puts gs_call
`#{gs_call}`
