#!/usr/bin/env ruby

pdf = ARGV.shift.sub(/$/, ".pdf")

marks = File.open('pdfmarks', 'w')

h = Hash.new

while gets() do
  #expect a header line and ignore it
  next if $. == 1
  h[:bm], h[:p] = $_.chomp.split("\t")
  
  #strip wrapping double quotes
  h.each_value{|v| v.sub!(/^"(.*)"$/, '\1')}

  ##squeeze doubled double quotes
  #h.each_value{|v| v.gsub!(/""/, '"')}
  
  #strip leading junk and zeros from page
  #FIXME we can probably grab the 1st page and offset all others from that?
  #or allow pgcount to be the last field
  h[:p].sub!(/.*[^0-9]0*/, '')

  marks.puts "[/Title (#{h[:bm]}) /Page #{h[:p]} /OUT pdfmark"
end

marks.close

puts %Q(gs -dBATCH -dNOPAUSE -sPAPERSIZE=letter -sDEVICE=pdfwrite -sOutputFile="#{pdf}" *.pdf pdfmarks)
